http:
 #region routers 
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`prox.plenty.wtf`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pi.plenty.wtf`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: pihole
    Unifi:
      entryPoints:
        - "https"
      rule: "Host(`unifi.plenty.wtf`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: unifi

#endregion
#region services
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.1.24:8006"
        passHostHeader: true
    unifi:
      loadBalancer:
        servers:
          - url: "https://192.168.1.5"
        passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: "https://192.168.1.2"
        passHostHeader: true   
             
#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
        # - "10.0.0.0/8"
        - "192.168.0.0/16"
        # - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers